services:
  flashrank-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override specific settings for Docker
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Mount models directory for persistence across container restarts
      - ./models:/app/models
      # Mount .env file
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Increased to allow model downloading
    networks:
      - proxy

networks:
  proxy:
    external: true